### ISSUE TITLE
Further thumbnail improvements

### ISSUE THREAD

**Issue by holtwick** [holtwick/pdfify#42]
- [ ] Reorder via Cut and Paste #30
- [ ] Indicate OCR status #36 
- [ ] Keyboard shortcuts #34
- [x] Reorder via Drag and Drop #30
- [x] Multiselect #34
